// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP3KaMZXSnM6Muah8RPczR3A4wQkc_4JA',
    appId: '1:286900333491:web:965e78d2f830d86c7839c6',
    messagingSenderId: '286900333491',
    projectId: 'chataloka-4d77a',
    authDomain: 'chataloka-4d77a.firebaseapp.com',
    storageBucket: 'chataloka-4d77a.firebasestorage.app',
    measurementId: 'G-JPF0QJCSFN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHavhk0ZYczTqR0TE_Otu7A4Idkrl6MtU',
    appId: '1:286900333491:android:63eee20abefaa3b57839c6',
    messagingSenderId: '286900333491',
    projectId: 'chataloka-4d77a',
    storageBucket: 'chataloka-4d77a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBPNyEmWpoemuKXgZhSChjXpbdqyQqjf0',
    appId: '1:286900333491:ios:5b6dc5e0e99474fb7839c6',
    messagingSenderId: '286900333491',
    projectId: 'chataloka-4d77a',
    storageBucket: 'chataloka-4d77a.firebasestorage.app',
    iosBundleId: 'com.rakafebriansy.chataloka',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAP3KaMZXSnM6Muah8RPczR3A4wQkc_4JA',
    appId: '1:286900333491:web:51fa4ad47c07a8dc7839c6',
    messagingSenderId: '286900333491',
    projectId: 'chataloka-4d77a',
    authDomain: 'chataloka-4d77a.firebaseapp.com',
    storageBucket: 'chataloka-4d77a.firebasestorage.app',
    measurementId: 'G-LH195FZJ4E',
  );
}
